[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

; change microcontroller
board_build.mcu = esp8266

; change MCU frequency
board_build.f_cpu = 80000000L
check_tool =
  cppcheck
check_skip_packages = yes
check_flags =
  cppcheck: --enable=warning,style,performance,portability --suppress=noExplicitConstructor
lib_deps =
  adafruit/Adafruit NeoPixel

